### ISSUE TITLE
Unable to authenticate using API docs examples

### ISSUE THREAD

**Issue by mariogintili** [zendesk/sunshine-conversations-javascript#72]
[I tried to replicate the example given on the docs using this NPM package](https://docs.smooch.io/guide/authenticating-to-smooch-api/).

As you can see on the demo recorded http://quick.as/p6eZfRJAR I was unable to do so. I didn't tried using an HTTP client and authenticating myself as I had chosen to try out smooch because it looked like a quicker start

**Comment by lemieux** [comment]
Hey @mariogintili ,

from your demo it seems like you are using a keyId/secret combination from your account and not from your app. You need an app-specific keyId/secret to send message. You can find that under the Settings tab at https://app.smooch.io.

Let me know if it works.

**Comment by alavers** [comment]
@mariogintili You can use a app-specific keyId/secret to send a message as @lemieux suggests, *or* you can use your account-level keyId/secret. Because account-level creds give you access to many apps, you need to specify which app you're targeting in your method call. You can do that by including it as the 1st parameter:

```
smooch.appUsers.sendMessage(appId, userId, {...})
```

Apologies for the confusion, the docs are not very clear on this .
