### ISSUE TITLE
Is there a way to implement event listeners using only Smooch Core?

### ISSUE THREAD

**Issue by rebelliard** [zendesk/sunshine-conversations-javascript#84]
The main Smooch library has built-in event listeners, but the tradeoff in bundled size is too big for me (50kb with Smooch Core vs 500kb with Smooch). Is there a way to implement this?

**Comment by mspensieri** [comment]
What kind of events are you wanting to listen for? The `Smooch` library will emit events when new messages are received, but it only runs in the context of a single user, and it's meant to be embedded on a web page to display a chat widget.

If you need your server to be notified of events affecting your Smooch app as a whole, [webhooks](https://docs.smooch.io/rest/#webhooks) would be the way to go.

**Comment by fli** [comment]
We're looking to implement a lighter version of the web messenger. So we want to have a way to be notified when the appUser (in the browser) receives a message from the appMaker, so we can show the message to the appUser in realtime. AFAIK, `smooch-core` in the browser (and the REST API in general) only provides a way to get the most recent 100 messages in a conversation, but no way to be notified of new messages.

Is there a way to do it using only `smooch-core` on the browser, or do you need to have a server with webhooks?

**Comment by mspensieri** [comment]
Ah, yes that's right, `smooch-core` doesn't include realtime messaging support, it wasn't really meant to be used as a standalone browser client - it's intended for server to server usage mostly. The `smooch` library doesn't use public APIs to accomplish that, so I wouldn't recommend trying to re-implement it since those APIs are likely to change without notice.

I guess if you wanted to re-implement this behaviour using only smooch core, you'd need to listen to webhooks on your server and maybe create your own realtime API over websockets
